### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by pvinis** [react-native-hooks/keyboard#12]
I'm making an issue as a way to reach out to you guys. We have https://github.com/react-native-community/react-native-hooks over at the react-native-community. Would you care you join us and have hooks there if we are missing something? Join forces? :D

**Comment by divyanshu013** [comment]
Hi @pvinis, that sounds great, would love to join you. Could you invite us over to the org (@divyanshu013, @pritishvaidya)? We can also help as maintainers if needed.

For any missing APIs or hooks we could create an issue. Thanks.

**Comment by pvinis** [comment]
You have both been invited to the hooks repo 🙌
