### ISSUE TITLE
useWillShow: true, useWillHide: true Not working on Android

### ISSUE THREAD

**Issue by lumberman** [react-native-hooks/keyboard#14]
Hey,
thanks for this library.

The hook isn't working on Android with the next settings:
```
useWillShow: true,
useWillHide: true,
```

**Comment by divyanshu013** [comment]
Thanks, will have to look into the issue. `react-native-community` has been working on some hooks which also has TS support. Would [this hook](https://github.com/react-native-community/hooks#usekeyboard) work for your usecase?

**Comment by lumberman** [comment]
> Would [this hook](https://github.com/react-native-community/hooks#usekeyboard) work for your usecase?
Didn't know about these. Thanks!
